a = float(input('Digite o valor de A: '))
b = float(input('Digite o valor de B: '))
c = float(input('Digite o valor de C: '))
n = float(((a+b*c)-((a*b*c)**0.5))/(2*c+b))
print('O resultado é: ', n)